[package]
name = "netfun"
version = "0.1.0"
authors = ["wyc <wyc@fastmail.fm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3"
nom = "6"
rocksdb = "0.15"
ipnet = "2.3"
containers = "0.9"
